server:
  port: 8085
spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost/flight-reservationdb?useLegacyDatetimeCode=false&serverTimezone=Europe/Amsterdam&useSSL=false
    username: root
    password: 913389696@Ww
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
